# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Amirhossein Bayat
first_name: Amirhossein
last_name: Bayat

contact_note: >
  Email is best. I’m also reachable by phone on weekdays.
description: >
  PhD candidate (SDU) in mechanical engineering. I work on density-based topology
  optimization for fluid mechanics (TuTO), CFD (Navier–Stokes, RANS k-ε), and
  adjoint sensitivities.

# Contact + media
email: "abay@sdu.dk"           # picked up by jekyll-email-protect
phone: "+45 52 73 96 87"       # for About page/contact cards
avatar: assets/img/amir-profile.jpg   # your portrait (used by About)
og_image: assets/img/amir-og.jpg      # social preview (1200×630 recommended)

footer_text: >
  © {{ "now" | date: "%Y" }} Amirhossein Bayat · Built with
  <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> +
  <a href="https://github.com/alshedivat/al-folio">al-folio</a> ·
  Hosted on <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

keywords: topology optimization, CFD, Navier–Stokes, RANS k-epsilon, adjoint methods, SDU
lang: en
icon: ⚛️
url: "https://bayat-amirhossein.github.io"
baseurl: ""
last_updated: true
back_to_top: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------
max_width: 980px
enable_navbar_social: true
serve_og_meta: true
serve_schema_org: true
